version = 0.1

[default]
[default.global.parameters]
stack_name = "poker-room-dev"
s3_bucket = ""  # SAM will create bucket automatically
s3_prefix = "poker-room"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Environment=dev"

[prod]
[prod.global.parameters]
stack_name = "poker-room-prod"
s3_bucket = ""  # SAM will create bucket automatically
s3_prefix = "poker-room"
region = "us-west-1"
confirm_changeset = false  # Auto-confirm for prod
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Environment=prod"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true