/*
 * This source file was generated by the Gradle 'init' task
 */
package spades.nine.poker.room;

import java.util.ArrayList;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.UUID;
import java.util.logging.Logger;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import spades.nine.poker.room.api.CardsApi;
import spades.nine.poker.room.model.PlayingCard;
import spades.nine.poker.room.service.PlayingCardService;

public class CardsApiImpl implements CardsApi {
    public static final Logger LOGGER = Logger.getLogger(CardsApiImpl.class.getName());

    private final PlayingCardService playingCardService;

    public CardsApiImpl() {
        this(new PlayingCardService());
    }

    public CardsApiImpl(PlayingCardService playingCardService) {
        this.playingCardService = playingCardService;
    }

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        LOGGER.info(new CardsApiImpl().getGreeting());
    }

    @Override
    public List<PlayingCard> cardsGet() {
        return new ArrayList<>(playingCardService.getAllItems());
    }
    @Override
    public void cardsIdDelete(UUID id) {
        if(!playingCardService.deleteItem(id)) throw new NoSuchElementException();
    }

    @Override
    public PlayingCard cardsPost(@Valid @NotNull PlayingCard playingCard) {
        return playingCardService.createItem(playingCard);
    }
}
